package model;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TokenStatus {

    @JsonProperty("current_tokens")
    private int currentTokens;

    @JsonProperty("max_tokens")
    private int maxTokens;

    @JsonProperty("total_collected")
    private int totalCollected;

    @JsonProperty("time_until_next")
    private int timeUntilNext;

    @JsonProperty("time_until_auto")
    private int timeUntilAuto;

    @JsonProperty("can_collect")
    private boolean canCollect;

    @JsonProperty("auto_generated")
    private boolean autoGenerated;

    public int getCurrentTokens() {
        return currentTokens;
    }
    public void setCurrentTokens(int currentTokens) {
        this.currentTokens = currentTokens;
    }

    public int getMaxTokens() {
        return maxTokens;
    }
    public void setMaxTokens(int maxTokens) {
        this.maxTokens = maxTokens;
    }

    public int getTotalCollected() {
        return totalCollected;
    }
    public void setTotalCollected(int totalCollected) {
        this.totalCollected = totalCollected;
    }

    public int getTimeUntilNext() {
        return timeUntilNext;
    }
    public void setTimeUntilNext(int timeUntilNext) {
        this.timeUntilNext = timeUntilNext;
    }

    public int getTimeUntilAuto() {
        return timeUntilAuto;
    }
    public void setTimeUntilAuto(int timeUntilAuto) {
        this.timeUntilAuto = timeUntilAuto;
    }

    public boolean isCanCollect() {
        return canCollect;
    }
    public void setCanCollect(boolean canCollect) {
        this.canCollect = canCollect;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }
}
